version: '3'
networks:
  default:
    external:
      name: compose_container_services_networks
services:
  quantalmicroservicetemplate:
    build:
      context: ./../../
      dockerfile: ./docker/Dockerfile
    ports:
      - ${WEB_APP_PORT:-8080}:8080
    environment:
      - DB_HOST=postgres_quantalmicroservicetemplate
      # The DB_PORT env var has been left empty. Please set env var when starting container
      # for example, issue the command below to start
      # DB_PORT=5432 docker-compose -f docker/compose/docker-compose.yml up
      - DB_PORT
      - LOGZIO_TOKEN=${LOGZIO_TOKEN}
    # Note: The port specified in the wait-for-it.sh script is the port that the  container exposes on the coontainer  side and not
    # the host side
    command: ["/wait-for-it.sh", "-t", "30", "postgres_quantalmicroservicetemplate:5432", "--", "java -jar ~/quantalmicroservicetemplate-0.0.1-SNAPSHOT.jar"]
    volumes:
      - /private/var/docker/log/quantalmicroservicetemplate:/var/log
    #networks:
    #  - container_services_networks

  # The postgres database
  postgres_quantalmicroservicetemplate:
    restart: always
    image: sameersbn/postgresql:9.6-2
    ports:
      - ${DB_PORT_EXPOSED_ON_HOST:-5434}:5432
    environment:
      - DEBUG=false
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_NAME=postgres
      - PG_PASSWORD=postgres
      - DB_TEMPLATE=

      - DB_EXTENSION=

      - REPLICATION_MODE=
      - REPLICATION_USER=
      - REPLICATION_PASS=
      - REPLICATION_SSLMODE=
    #networks:
    #  - container_services_networks